INSERT INTO USERS(user_email,user_enabled,user_password,user_name) VALUES('2@2',TRUE,'$2a$10$WpH0TC5TephtkN/ZECovNOc3p2W4C6Ida.pBYEPBjTjwJA8oaYXPW','Sp1D')
INSERT INTO USERS(user_email,user_enabled,user_password,user_name) VALUES('1@2',TRUE,'$2a$10$WpH0TC5TephtkN/ZECovNOc3p2W4C6Ida.pBYEPBjTjwJA8oaYXPW','Cat Max')
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Simpsons (Anime, Thriller)',1,1)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Terminator 18',1,1)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Cat Max: Fur road',2,2)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Aladdin',1,2)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Breaking Bad S01',2,1)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Breaking Bad S02',2,1)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Breaking Bad S03',2,2)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Breaking Bad S04',2,2)
INSERT INTO DISKS(disk_title, disk_owner, disk_holder) VALUES('Breaking Bad S05',2,2)
